### ISSUE TITLE
Fingerprint not working on Infinix note 7

### ISSUE THREAD

**Issue by pixelextend** [mytja/treble_evo#10]
How can i fix play integrity, Fingerprint

**Comment by mytja** [comment]
Play Integrity passes device with integrated PIF app, device with external PIF Magisk module, and strong using PIF (app or Magisk module) and TrickyStore.

As for fingerprint, if it doesn't work on [TrebleDroid GSI](https://github.com/TrebleDroid/treble_experimentations/), then [report the issue on their end](https://github.com/TrebleDroid/treble_experimentations/issues).
