### ISSUE TITLE
Bluetooth Issue in the lasted build v9.7 and Pixel Launcher shows stops once I unlock the phone.

### ISSUE THREAD

**Issue by mdsyfulislam3249** [mytja/treble_evo#100]
Please kindly fix these issues ASAP—other than everything so smooth.

**Comment by mytja** [comment]
#94

Closing as a duplicate

Other than that, Pixel Launcher showing stops only after unlock? I don't quite understand.

**Comment by mdsyfulislam3249** [comment]
It's working fine but the pop-up msg rarely shows, not every time.
