### ISSUE TITLE
FOD

### ISSUE THREAD

**Issue by kjimoh** [mytja/treble_evo#106]
FOD not fixed on Redmi Note 13 Pro 4g

**Comment by kjimoh** [comment]
![Screenshot_20241226-103709_Settings](https://github.com/user-attachments/assets/ab3116cf-851e-43cc-952a-a3389f11c62c)


Log url:
https://paste.evolution-x.org/GgNmcj

**Comment by mytja** [comment]
I've fixed the crash in the newest release. As per FOD, it might work or might not start working. It's a gamble. If it doesn't work in any other GSI, I am not likely to fix it.

https://github.com/mytja/treble_evo/releases/tag/20241226
