### ISSUE TITLE
 Charging Percentage Not Displayed When Phone is Powered Off (Evolution X 9.5, 9.6, 9.7)

### ISSUE THREAD

**Issue by julfikar9999** [mytja/treble_evo#109]
Hello Evolution X Team,
I am reporting a consistent bug present in Evolution X versions 9.5, 9.6, and 9.7.
Description of the issue:
When the phone is powered off and connected to a charger, the charging percentage is not displayed on the screen. While the charging icon (like a battery icon) appears as it should on powered-off devices, the actual percentage of charge is not shown. This makes it difficult to know how much the battery has charged without turning on the device.
Steps to reproduce:
 * Power off the phone completely.
 * Connect the phone to a power source using a charging cable.
 * Observe the screen.
Expected behavior:
The screen should display the current charging percentage along with the charging icon, similar to how it behaves on other ROMs or stock Android.
Actual behavior:
The screen shows the charging icon (battery icon), but the percentage of charge is missing.
Affected devices:
This issue has been observed across multiple devices running Evolution X 9.5, 9.6, and 9.7.
Additional information:
This issue has been consistently observed across Evolution X versions 9.5, 9.6, and 9.7.
I hope this information is helpful in identifying and resolving the issue. Thank you for your time and attention to this matter.
Sincerely,

**Comment by SMOLKEYS** [comment]
This is _very_ likely intentional. Some implementations of offline charging may or may not include showing the battery percentage.

A percentage indicator _would_ be preferable though. You don't have much to go off of with just five static battery images.

**Comment by mytja** [comment]
Yeah, I've had some issues with Evolution X's Pixel Charger while building, so I just removed it completely. It looks like this AOSP charger has now been used instead. Will try nuking AOSP charger and reintroducing Pixel Charger in the January build.

**Comment by mytja** [comment]
Fixed in the latest test image:

GitHub: https://github.com/mytja/treble_evo_test/releases/tag/20241230-test3-bt-charger
Mirror: https://git.severkar.eu/mytja/treble_evo_test/releases/tag/20241230-test3-bt-charger

I won't do a full release, as I've pledged I won't release any more releases this year. So this should be sufficient for now.
