### ISSUE TITLE
No booted in xiaomi redmi 10 2022 (selene)

### ISSUE THREAD

**Issue by HKMGER** [mytja/treble_evo#11]
The rom does not start on the xiaomi redmi 10 2022 it stays loading on the logo and after a few minutes it restarts in the original boot and one in the a / b slot

**Comment by mytja** [comment]
Yeah, sorry, can't help with this one. I've applied all appropriate patches. Google has also nerfed ADB when booting, so nothing useful can be done here. If you obtain any logs, go ahead and provide them, however nothing much can be done without them...
