### ISSUE TITLE
Does this gsi rom work on mediatek devices?

### ISSUE THREAD

**Issue by M0d-4** [mytja/treble_evo#113]
specifically redmi note 13 pro+

**Comment by SMOLKEYS** [comment]
Well, I use a MediaTek device, and it boots, so... yes, I suppose?

**Comment by SMOLKEYS** [comment]
How stable a GSI is can depend on your device. For some, it may work fine, for others, it may not.

**Comment by mytja** [comment]
Try it and see for yourself.
