### ISSUE TITLE
[info] the bluetooth bug is fixed on the latest AOSP release by trebledroid , i tried and tested it , bluetooth works fine

### ISSUE THREAD

**Issue by Technical06** [mytja/treble_evo#114]

**Comment by mytja** [comment]
This release has a confirmed working Bluetooth on Mediatek:

https://github.com/mytja/treble_evo_test/releases/tag/20241230-test3-bt-charger

Reopen the issue if it isn't fixed.

**Comment by Technical06** [comment]
> This release has a confirmed working Bluetooth on Mediatek:
> 
> https://github.com/mytja/treble_evo_test/releases/tag/20241230-test3-bt-charger
> 
> Reopen the issue if it isn't fixed.

okay on my way

**Comment by Technical06** [comment]
> This release has a confirmed working Bluetooth on Mediatek:
> 
> https://github.com/mytja/treble_evo_test/releases/tag/20241230-test3-bt-charger
> 
> Reopen the issue if it isn't fixed.

youre so active for the community , are you on telegram so i can contact you , and maybe help you fix bugs or issues in some way , or help you test images

BTW a very happy new year to you ❤️

**Comment by Technical06** [comment]
> This release has a confirmed working Bluetooth on Mediatek:
> 
> https://github.com/mytja/treble_evo_test/releases/tag/20241230-test3-bt-charger
> 
> Reopen the issue if it isn't fixed.

youre so active for the community , are you on telegram so i can contact you , and maybe help you fix bugs or issues in some way , or help you test images

**Comment by Technical06** [comment]
> This release has a confirmed working Bluetooth on Mediatek:
> 
> https://github.com/mytja/treble_evo_test/releases/tag/20241230-test3-bt-charger
> 
> Reopen the issue if it isn't fixed.

Now the issue has been fixed , at first it gave same problem but now it is fixed
