### ISSUE TITLE
weird overlay sizing on Galaxy A53 5G

### ISSUE THREAD

**Issue by soxzko** [mytja/treble_evo#12]
status bar height is weird, tried to fix it but failed

**Comment by Marcos-Dtel** [comment]
![Screenshot_20240908-005326_Edge~2](https://github.com/user-attachments/assets/b3fe8dee-151a-4de3-9d65-88010cc8eee2)

**Comment by mytja** [comment]
I've diagnosed the issue and resolved it. October release will fix it.

**Comment by mytja** [comment]
Overlays have been fixed in the latest beta release

https://github.com/mytja/treble_evo/releases/tag/20240921
