### ISSUE TITLE
Holding the home button to call circle search doesn't work

### ISSUE THREAD

**Issue by Vad1mCSO2** [mytja/treble_evo#13]
Due to deletion on gemini at September 5th, 2024. Works fine on 9.3 + dirty flash 9.4

**Comment by mytja** [comment]
Okay, will readd it, I though it was useless.

**Comment by Vad1mCSO2** [comment]
Also make a pre-release image build

**Comment by mytja** [comment]
Why?

**Comment by Vad1mCSO2** [comment]
I wanted to test this rom before release

**Comment by Marcos-Dtel** [comment]
![Screenshot_20240910-071726_Google](https://github.com/user-attachments/assets/9f07ca29-ac01-4e9c-8b2f-bac6920d2436)
I added this manually

**Comment by mytja** [comment]
Readded in latest beta release. Thanks

https://github.com/mytja/treble_evo/releases/tag/20240921

**Comment by Vad1mCSO2** [comment]
> Readded in latest beta release. Thanks
> 
> https://github.com/mytja/treble_evo/releases/tag/20240921

@mytja Thank you so much! I will testing this β ROM
