### ISSUE TITLE
Bluetooth Problem

### ISSUE THREAD

**Issue by pixelextend** [mytja/treble_evo#15]
Bluetooth Problem, when Changing YouTube videos, Bluetooth will stop running.

**Comment by mytja** [comment]
Are you opening issues just to annoy me? Please write what you did to resolve it or just say "I have skill issue".

At this point it seems like you have more problems than the GSI itself. Go over to TrebleDroid and open an issue there if your device isn't supported, however don't waste my time here, as I'm certainly not a HAL/Android expert.
