### ISSUE TITLE
Sim Slot's 

### ISSUE THREAD

**Issue by pixelextend** [mytja/treble_evo#16]
There is showing 3 sim Slot's, but i just only have 2 Slot's, why it happened with me in all gsi ROM

**Comment by mytja** [comment]
If it's going on in all GSIs, then your device isn't properly supported. Again, will repeat it only once more, open a ticket at TrebleDroid, they'll know how to help much better than I can.

**Comment by pixelextend** [comment]
@mytja Bro, can you help me how i fix this issue.![markup_1257.jpg](https://github.com/user-attachments/assets/7c0dbcfa-2f67-4019-9443-d7eef55a3471)

![markup_1263.jpg](https://github.com/user-attachments/assets/25779e59-9bbd-4441-bded-75d6c6186bd4)

**Comment by mytja** [comment]
https://github.com/mytja/treble_evo/issues/27#issuecomment-2365303917
