### ISSUE TITLE
status bar

### ISSUE THREAD

**Issue by armanozdmr** [mytja/treble_evo#2]
phhtreble settings to set the status bar diameter values don't work. I've tried restarting system ui and the phone so far nothing. the left top clock is just behind the screen. One temp fix I found is to add a logo to the left of the clock but I couldn't find a way to make it transparent

**Comment by mytja** [comment]
Yeah, this is a bug. Will be fixed in next release.

**Comment by 123456sanjib** [comment]
Can you open a telegram group for your gsi?

**Comment by mytja** [comment]
No, sorry. I'm in some Telegram groups and the amount of irrelevant spam that's allowed in there is insane, so I'd rather stay away as possible as I can. Apart from that, I think GitHub Issues are far better in organizing and classifying issues that need to be resolved than Telegram is.

**Comment by 123456sanjib** [comment]
Ok, as you wish.

**Comment by mytja** [comment]
Fixed in newest release.

https://github.com/mytja/treble_evo/releases/tag/20240905
