### ISSUE TITLE
Face unlock missing on Galaxy A54 (SM-A546E)

### ISSUE THREAD

**Issue by Frios-e-lacticinios** [mytja/treble_evo#20]
the facial unlock simply doesn't appear, I found this very bad, and the fingerprint doesn't work (but this is GSI's problem with the a54)

**Comment by iUnkownPlayer** [comment]
The fact that the facial recognition system does not work is related to the ROM, and this is stated in the section about bugs.

**Comment by mytja** [comment]
Face unlock has been added in the latest beta release.

https://github.com/mytja/treble_evo/releases/tag/20240921
