### ISSUE TITLE
not install DSU

### ISSUE THREAD

**Issue by Quanquan6169Vietnamese** [mytja/treble_evo#21]
![Screenshot_20240916-131151_DSU Sideloader](https://github.com/user-attachments/assets/4bcf8536-a192-46e4-a336-68b8b890a716)

**Comment by mytja** [comment]
Do you have too little free space on your device? Your userdata is set to 8GB. It's not an issue with the GSI itself, but with DSU.

**Comment by Quanquan6169Vietnamese** [comment]
you can try installing on your phone, to find out the error caused by your
rom version,

Vào 13:15 Th 4, 18 thg 9, 2024 ᄀ샬배어 ***@***.***> đã viết:

**Comment by mytja** [comment]
It's not an issue with my GSI. It can be installed through DSU on my device. If you have too small of a system partition, you could try the slim version.

**Comment by Quanquan6169Vietnamese** [comment]
Do you know the reason why calls are received, but SMS messages are not
received? Some of my ROM versions, sometimes I have to reboot the device
several times before receiving SMS messages.

Vào 18:13 Th 4, 18 thg 9, 2024 ᄀ샬배어 ***@***.***> đã viết:

**Comment by Quanquan6169Vietnamese** [comment]
I really like your current ROM because your sms waves work normally, and
everything is customizable

Vào 18:30 Th 4, 18 thg 9, 2024 ᄀ샬배어 ***@***.***> đã viết:

**Comment by Quanquan6169Vietnamese** [comment]
I have installed dynamic system update (DSU) on other roms and nothing
happens.

Vào 18:31 Th 4, 18 thg 9, 2024 ᄀ샬배어 ***@***.***> đã viết:

**Comment by mytja** [comment]
> Have you tested when successfully installing the dynamic system image?

Yes. It has installed successfully through DSU.

> Do you know the reason why calls are received, but SMS messages are not
received? Some of my ROM versions, sometimes I have to reboot the device
several times before receiving SMS messages.

If it's a Samsung device, these have messed up IMS.

> I have installed dynamic system update (DSU) on other roms and nothing
happens.

Then you have a broken DSU.

**Comment by Quanquan6169Vietnamese** [comment]
yes my device is samsung, do you know how to fix ims

Vào 18:37 Th 4, 18 thg 9, 2024 Mitja Ševerkar ***@***.***> đã
viết:

**Comment by mytja** [comment]
I installed FLOSS IMS and it suddenly worked. If that doesn't work, you need RIL rollback module for Magisk/KSU.

**Comment by Quanquan6169Vietnamese** [comment]
If my DSU fails, I will return EvolutionX8.3(ngankbka) This rom everything
works fine Only error per ims

Vào 18:43 Th 4, 18 thg 9, 2024 Mitja Ševerkar ***@***.***> đã
viết:

**Comment by Quanquan6169Vietnamese** [comment]
Can you guide me to fix ims, or an available instruction link is available

Vào 18:45 Th 4, 18 thg 9, 2024 ᄀ샬배어 ***@***.***> đã viết:

**Comment by mytja** [comment]
FLOSS IMS can be installed from here: https://treble.phh.me/floss-ims-19-resigned.apk

After installing it, a visit to Phh Settings -> IMS Settings -> Create IMS APN or something similar should be needed. A reboot may be required, though unlikely.

I've heard it doesn't work on every device. I'm not even sure it works on mine. I used to have SMS problems on all GSIs but now with EvoX there are suddenly no SMS issues.

RIL rollback libraries & respective tutorials can be found all over the internet:
- https://xdaforums.com/t/solved-gsi-related-can-not-receive-sms.4636173/
- https://xdaforums.com/t/fix-for-samsung-s21-fe-5g-gsi-no-sms-received-problem.4646395/
- https://xdaforums.com/t/sms-fix-for-exynos-devices-running-a-gsi.4658849/
- https://kernelpanik.net/fix-sms-reception-on-samsung-s20-fe-5g/

**Comment by Quanquan6169Vietnamese** [comment]
Unfortunately my Samsung device runs on a Snapdragon chip

Vào 22:53 Th 4, 18 thg 9, 2024 Mitja Ševerkar ***@***.***> đã
viết:

**Comment by Quanquan6169Vietnamese** [comment]
I tried everything but still to no avail. I installed the fixSMS.zip
through magisk but it did not receive 5G+volte signal (it became an
emergency call).

Vào 0:44 Th 6, 20 thg 9, 2024 Mitja Ševerkar ***@***.***> đã
viết:

**Comment by Quanquan6169Vietnamese** [comment]
IMS features: Create IMS APN, still no change. Misc features: check
Automatically restart RIL The results remained unchanged, No special
settings or changes, ims still works normally except sms. I searched for
this problem on Google and read many articles, but still to no avail

Vào 11:06 Th 6, 20 thg 9, 2024 ᄀ샬배어 ***@***.***> đã viết:

**Comment by Quanquan6169Vietnamese** [comment]
I installed gsi of evolutionX-8.3_arm64_bgN-RO.img.xz because version 9.0
doesn't work on my phone, I installed
evolution_arm64_bgN-9.4-unofficial-20240906.img.xz into the dynamic system,
this version ims always works, no matter how many times I restart the
system, it always works well.

Vào 11:13 Th 6, 20 thg 9, 2024 ᄀ샬배어 ***@***.***> đã viết:

**Comment by Quanquan6169Vietnamese** [comment]
Have you installed the usb otg driver to read exfat formatted memory cards?
Almost every gsi version that inserts a memory card shows a problem with
the usb.

Vào 11:18 Th 6, 20 thg 9, 2024 ᄀ샬배어 ***@***.***> đã viết:

**Comment by mytja** [comment]
I don't install exFAT modules. It's your kernel's job to do that. Please move the discussion about exFAT modules over to this issue: https://github.com/mytja/treble_evo/issues/17.

It'd be also very helpful if somebody would execute the following `adb shell cat /proc/filesystems` and send me the output.

**Comment by Quanquan6169Vietnamese** [comment]
Until now I still haven't found a way to successfully install the dynamic system on your evobeta version, I still get the error that I can't create a partition, I still don't have a file to access the root data/gsi/dsu/dsu file. Which is specially installed in there!
