### ISSUE TITLE
Update to latest evoX sources 

### ISSUE THREAD

**Issue by ahmedAMZ** [mytja/treble_evo#25]
Please update evox sources to fix face unlock
Because their Latest update they added many changes since you released your gsi

Thanks for your efforts

**Comment by mytja** [comment]
No need to rush. Update will come in October, no earlier. I needed a break from all the issues.

**Comment by ahmedAMZ** [comment]
Trust me I know evoxX since years
Sometimes you have good version in particular month 
In next month , rom update may ruin rom and comes with new bugs

This month we have really good version, please take the opportunity and update your rom

**Comment by mytja** [comment]
Okay, you've got yourself a deal :smile:.

I'll release a beta version within a couple of hours, fixing many bugs.

**Comment by ahmedAMZ** [comment]
Many thanks friend

**Comment by mytja** [comment]
https://github.com/mytja/treble_evo/releases/tag/20240921

**Comment by ahmedAMZ** [comment]
Thanks friend
