### ISSUE TITLE
Clock icon cant fit at A53

### ISSUE THREAD

**Issue by iUnkownPlayer** [mytja/treble_evo#27]
i installed myjta's evo x but I have problem the top bar hour icon its not fitting into my screen. For example The clock icon is showing 22.05 but the first number cutting out from my screen how can i fix it?

**Comment by mytja** [comment]
Phh Treble Settings > Misc features >  Set status bar start padding

If this value is set to -1, set it to something higher, for example 24 or 48, otherwise set it to -1.

This requires restart.

**Comment by pixelextend** [comment]
@mytja nothing happened, but when i use your previous Gsi image it works fine and status bar looks perfect but i don't know what happen with my phone.
Thanks for your response 👍

**Comment by mytja** [comment]
In beta I've added overlays. Set status bar start padding should override overlays (and it does on my phone), maybe try higher numbers (values are in pixels and 24 pixels are not that visible), especially if you have the notch on the left.

**Comment by pixelextend** [comment]
It's working on front screen, but can't work when i pull down status bar (Qs Panel).

**Comment by mytja** [comment]
Yeah, that I'd need to fix with another patch. I might add it in future.

**Comment by pixelextend** [comment]
Thank you 😊 @mytja

**Comment by pixelextend** [comment]
Need to fix Bluetooth random restart
