### ISSUE TITLE
Showing wrong IMS vendor on mtk

### ISSUE THREAD

**Issue by N3Shemmy3** [mytja/treble_evo#28]
![Screenshot_20240921-223242_PhhTrebleApp](https://github.com/user-attachments/assets/1f44dd10-e25a-448d-bfd1-e86fa12ab3f0)
As you can see from the screenshot it says R+ when in fact my vendor is S and without the correct IMS my network is very unstable 

If possible could you please build the IMS apks and release them so that we can just install the correct ones ?

**Comment by mytja** [comment]
This is intended by TrebleDroid developers.

I don't have the knowledge to make builds, however you can download the resigned versions through https://treble.phh.me/stable/.
