### ISSUE TITLE
Compatible gcam for evolution x

### ISSUE THREAD

**Issue by iUnkownPlayer** [mytja/treble_evo#29]
Do you know which version of gcam is compatible with evo x?

**Comment by mytja** [comment]
Depends on your phone model. Ahnet's EvoX used GCam Go which is compatible with all devices and can be downloaded & installed from here:

https://github.com/ArrowOS-Devices/android_packages_apps_GCamGOPrebuilt/raw/refs/heads/arrow-13.1/GCamGOPrebuilt-v3_8.apk
