### ISSUE TITLE
Can't enable camera2api on A53

### ISSUE THREAD

**Issue by iUnkownPlayer** [mytja/treble_evo#34]
I tried ADB, Termux, magisk modules and the changing build.prop file but none of them worked on Galaxy A53 how can I enable camera2api on a53?

**Comment by mytja** [comment]
Camera2 API is enabled by default. Additional camera support can be enabled using Phh Treble > Samsung features > Enable access to all cameras.

**Comment by Vad1mCSO2** [comment]
I have enabled this option on A32 works fine mostly but semi unstable for errors or crashes

**Comment by Vad1mCSO2** [comment]
There are examples for Samsung Galaxy A32 4G
Normal ▽▼△▽
![2024-09-30-18-54-38-066](https://github.com/user-attachments/assets/0d2ee26f-c09b-43a0-9756-a05cd2b9e779)
Wide ▽▽△▼
![2024-09-30-18-54-44-411](https://github.com/user-attachments/assets/9813c479-0d46-4c69-8f9a-d210279ba399)
Macro ▽▽▲▽
![2024-09-30-18-54-50-024](https://github.com/user-attachments/assets/7ba595f2-bc84-4447-bdd3-7fcba498b29c)
Monochrome (Unused?) ▼▽△▽
![2024-09-30-18-54-58-016](https://github.com/user-attachments/assets/7af4d7f2-ec5c-4fad-8101-555f035c764e)

**Comment by mytja** [comment]
> I have enabled this option on A32 works fine mostly but semi unstable for errors or crashes

Then disable it. This option should only add the virtual monochrome camera, other cameras should be accessible by default.

**Comment by Vad1mCSO2** [comment]
> > I have enabled this option on A32 works fine mostly but semi unstable for errors or crashes
> 
> Then disable it. This option should only add the virtual monochrome camera, other cameras should be accessible by default.

When disabling disables all cameras except normal and front. When enable this option enables all cameras

**Comment by Vad1mCSO2** [comment]
@mytja Disabled Option [Default]
![Screenshot_20241002-150448_Камера](https://github.com/user-attachments/assets/236b1ab1-b67f-46fa-96e6-e71a25d4cee6)
Enabled Option
![Screenshot_20241002-151920_Камера](https://github.com/user-attachments/assets/63096c56-cf66-4afb-b7e1-4207b91c991c)
![Screenshot_20241002-151905_Камера](https://github.com/user-attachments/assets/a1ba52d8-abe3-4f9c-b902-026b15ca7901)
![Screenshot_20241002-151914_Камера](https://github.com/user-attachments/assets/01a4a332-9bfc-4c93-ba36-28a22c2cb773)
This is not a virtual in monochrome camera

**Comment by Vad1mCSO2** [comment]
![Photo0043](https://github.com/user-attachments/assets/f5a52b11-1c93-4855-b283-f2451840f95c)
![Photo0044](https://github.com/user-attachments/assets/265d6b20-a69c-4d1d-a34f-8491c2c47a48)

**Comment by mytja** [comment]
Can't reproduce.
