### ISSUE TITLE
problem with the frontal camera a21s

### ISSUE THREAD

**Issue by Tima592** [mytja/treble_evo#36]
hello, the firmware is very cool, everything works great, but there is one problem, the front camera of my phone is in the left corner of my screen and it blocks incoming notifications, it just covers it and I can’t see anything.

**Comment by Tima592** [comment]
![Без названия](https://github.com/user-attachments/assets/607b39ae-e435-47de-8cfe-8c853fa2be7d)

**Comment by mytja** [comment]
Does this happen on all GSIs or only my EvoX GSI? If this happens on only mine, go into Phh Treble Settings > Misc features > Set status bar start padding. Set the value to -1 if not already set or to some bigger value, such as 48. Experiment with the values and eventually you'll find the sweet spot. This requires phone reboot.

**Comment by Tima592** [comment]
> Это происходит на всех GSI или только на моем EvoX GSI? Если это происходит только на моем, перейдите в Phh Treble Settings > Misc features > Set status bar start padding. Установите значение -1, если оно еще не установлено, или на какое-то большее значение, например 48. Поэкспериментируйте со значениями, и в конечном итоге вы найдете золотую середину. Для этого требуется перезагрузка телефона.

thanks in advance for the answer, unfortunately this only happens on your GSI but I’ll try to do what you said thanks again for the answer

**Comment by mytja** [comment]
I guess this is fixed in the latest release. If not, use the _Set status bar start padding_ setting, available inside Phh Treble Settings, as mentioned beforehand.

If you have any issues with that feature, reopen the issue.
