### ISSUE TITLE
Difference between "normal" and slim?

### ISSUE THREAD

**Issue by imbroglius** [mytja/treble_evo#4]
Could you please provide what is different in both versions?

**Comment by mytja** [comment]
Evolution X offers three different GMS (Google Mobile Services) versions, as can be seen [here](https://bitbucket.org/evo-x/vendor_gms/src/udc/).

The slim version uses Pico GMS, whilst normal one uses the "full" GMS. Essentially, there's no real difference, apart from having less Google bloat preinstalled, which can therefore be installed later from the Google Play Store. It's mostly useful for devices with smaller system partitions.

Vanilla version is the version without Google Mobile Services.
