### ISSUE TITLE
What about superuser?

### ISSUE THREAD

**Issue by azraillo** [mytja/treble_evo#42]
title

**Comment by mytja** [comment]
What what about superuser?

**Comment by azraillo** [comment]
will there be a ROM with root?

**Comment by mytja** [comment]
Nope. SuperSU and other forks are not common anymore, and that's for a good reason. Magisk, KernelSU and APatch are all insanely good root methods, offering way more flexibility and more ways to hide themselves. But I agree they are not that easy to install.
