### ISSUE TITLE
Implement some tweaks

### ISSUE THREAD

**Issue by pixelextend** [mytja/treble_evo#44]
Thanks Mytja for this Gsi

I face some issues such as
-battery is drain very quickly even in idle state
-bluetooth is randomly crash or disconnect 
-Try to add turn on and turn off sim card slots feature if possible, if it doesn't implement so add this feature Combined WiFi and mobile data icon if possible 
These issues i face on my device even i try another gsi, if it is possible to add these features so please add this in Gsi 

Thanks Mytja 🙂

**Comment by Kevinco1** [comment]
Do you have non Snapdragon model? If so the Bluetooth issue is related to Treble and you'll need to send them logs 

EvoX is very heavy compared to other GSIs, you can save battery by debloating once it's properly flashed

**Comment by pixelextend** [comment]
> Do you have non Snapdragon model? If so the Bluetooth issue is related to Treble and you'll need to send them logs
> 
> EvoX is very heavy compared to other GSIs, you can save battery by debloating once it's properly flashed



> Do you have non Snapdragon model? If so the Bluetooth issue is related to Treble and you'll need to send them logs
> 
> EvoX is very heavy compared to other GSIs, you can save battery by debloating once it's properly flashed

How i send you Log, tell me the method then i will send to you

**Comment by mytja** [comment]
```
adb logcat > log.txt
```

**Comment by pixelextend** [comment]
@mytja should i use this command ? 
Adb logcat -b crash > log.txt

**Comment by pixelextend** [comment]
But is it safe i send you publicaly logcat file ?, it doesn't have my sensitive data ?

**Comment by mytja** [comment]
It might contain sensitive data. If you're worried about it, I'm also available through mail on mytja@proton.me. Or you can send a link that expires after one download or something similar.

**Comment by mytja** [comment]
>  -bluetooth is randomly crash or disconnect

Have you already tried this?

https://matjaz.it/simple-fix-for-bluetooth-audio-not-working-on-android-10/

**Comment by pixelextend** [comment]
It has no option

**Comment by pixelextend** [comment]
I check it, but there is no option 
![Screenshot_20241017-205846_Pixel Launcher](https://github.com/user-attachments/assets/d37d2a06-21d6-4849-86b7-994e78b6bc76)

**Comment by Vad1mCSO2** [comment]
I also got battery no optimization at release. In previous version was optimised

**Comment by mytja** [comment]
> -Try to add turn on and turn off sim card slots feature if possible

This has been added in the latest beta release: https://github.com/mytja/treble_evo/releases/tag/20241028

Beware that it might make your telephony system unstable and I'm not sure if it'll work on your device.

I haven't had time to look at your logs, @pixelextend. Sorry for that.

Battery optimization is very relative though. On my device (Samsung A53) battery usage was constant through all the updates. This is likely issue with bloat (for example apps). I'd recommend a clean flash and installing only the apps needed. It has very little to do with the ROM (in this case Evolution X), as no major changes that drain battery fast are accepted into LineageOS/Evolution X. However it might be that some system apps are constantly crashing and that's causing the fast battery drain.
