### ISSUE TITLE
Strong? 

### ISSUE THREAD

**Issue by Kevinco1** [mytja/treble_evo#46]
The notes for the latest build say it passes strong but I'm not even getting basic with the built in spoof.

Has it been banned by Google? Just don't know if I'm doing anything wrong

**Comment by mytja** [comment]
Notes don't say it passes STRONG by default. Integrated PIF is enough to pass DEVICE verdict. ROM is signed.

The only thing I could think of is that you have a superuser, which is detected by DroidGuard. Check if /system/xbin/su exists and manually update to the latest release, which I'm currently running and can confirm it doesn't have the superuser.

**Comment by Kevinco1** [comment]
> Notes don't say it passes STRONG by default. Integrated PIF is enough to pass DEVICE verdict. ROM is signed.
> 
> The only thing I could think of is that you have a superuser, which is detected by DroidGuard. Check if /system/xbin/su exists and manually update to the latest release, which I'm currently running and can confirm it doesn't have the superuser.

Forgot to mention my actual device which is Samsung Tab A8, SM-200

I clean flashed the latest build and and do not have Superuser. However, I think I misunderstood....as you pointed out it does not pass strong by default so I guess it's more on what device each user has and this is not capable with the SM-X200

**Comment by mytja** [comment]
Play Integrity Fix should not be device-dependent. Maybe try checking if you have an outdated PIF module in Magisk/KernelSU or something similar. Some older modules interfere with the integrated PIF.

**Comment by Kevinco1** [comment]
> Play Integrity Fix should not be device-dependent. Maybe try checking if you have an outdated PIF module in Magisk/KernelSU or something similar. Some older modules interfere with the integrated PIF.

When I originally flashed the latest build I made sure not to install any Play Integrity modules. The spoofing was enabled by default in the Evolver settings and the device was certified until I wiped both Play Store and Services. This is when it became not certified for whatever reason
