### ISSUE TITLE
Deep Sleep doesn't work on Lenovo TB J716F

### ISSUE THREAD

**Issue by SipT1k** [mytja/treble_evo#48]
![Screenshot_20241011-210155_Settings 1](https://github.com/user-attachments/assets/32efc1ff-ad4e-48ee-a978-a87e94829880)
![Screenshot_20241012-075546_Settings 1](https://github.com/user-attachments/assets/3f0d3c73-bfb4-4372-a9a6-cc6eae4c8a63)

**Comment by mytja** [comment]
So your tablet just doesn't report deep sleep (it puts apps to deep sleep, but doesn't count it) or does it never force apps to deep sleep?

Does it happen on all GSIs or just this one? If it happens just on this one, I'll need some logs captured using `adb logcat`.

**Comment by SipT1k** [comment]
It has the battery drain while the table is locked (it looses about 15% at night). I see this problem at new GSI ROMs (A14). I'll investigate more when I arrive home.
Thanks for your reply

**Comment by SipT1k** [comment]
Ops, I closed the issue accidentally =)

**Comment by GyuminLeo** [comment]
it may be com.android.phone crashing in the background constantly
try using logfox app with root or shizuku to see if there are apps crashing in the background

I also have the same tablet and was reporting 0% deep sleep on most roms but after deleting com.android.phone it was still reporting as 0% deep sleep but the battery drain was reduced

**Comment by mytja** [comment]
Oh, I see now that I've been doing some work on patches. Yes, com.android.phone is indeed crashing. I think the appropriate solution would be to (if you have that option) click on Phh Treble Settings > Misc features > Telephony (section) > Remove Telephony Subsystem. However this likely won't work, as most devices are now RO-system.

Instead a Magisk/KernelSU module should be used to remove the telephony subsystem. I might provide it in a couple of hours if I'll still be awake and ready to do such a thing by then. Otherwise ping me tomorrow.

**Comment by SipT1k** [comment]
I've tried to delete the com.android.phone and it fix the issue about the battery draining but the problem with deep sleep counter doesn't solve. But my major problem was solved thank you for you help, and by the way I've attached some logs
[com.android.phone_crashing.zip](https://github.com/user-attachments/files/17563130/com.android.phone_crashing.zip)

[Deep sleep doesn't show up.zip](https://github.com/user-attachments/files/17563135/Deep.sleep.doesn.t.show.up.zip)

**Comment by GyuminLeo** [comment]
After deleting com.android.phone try opening the settings app
on some roms once you delete com.android.phone the networks page in the settings doesn't work thus resulting in the settings app crashing

If your rom also has that issue reinstalling com.android.phone will fix the issue

And for the deep sleep counter I didn't find a way to fix it bc it really doesn't matter alot to me

If you have root access I would recommend checking out FDE.AI app on github. It controls the processor speed for thermal and stuff and has the option for force doze mode. Even if the deep sleep counter doesn't go up turning on force doze mode in FDE.AI really improved my battery life

**Comment by mytja** [comment]
Never mind, the patch is already applied from LineageOS. I really need to get some rest. A lot of the issues are coming from tablets/devices without modems, and I'm not really sure why. Sorry for the unnecessary comments (and subsequently emails). This looks resolved to me, I'll close the issue.

If this isn't resolved, go ahead and comment/reopen the issue.

**Comment by SipT1k** [comment]
Okay, thanks! You should have some rest. I will try FDE.AI

**Comment by SipT1k** [comment]
I've installed FDE.AI turn on Doze mode in that program, Deep Sleep is reported now =)
