### ISSUE TITLE
X input support for rooted and/or non-root phone

### ISSUE THREAD

**Issue by Vad1mCSO2** [mytja/treble_evo#49]
I have 2.4GHz gamepad with USB wireless adapter will no working. I found this repository but, disappointed (no bumps for latest android version). This gamepad has no Bluetooth connection, only USB wireless adapter. I tested gamepad tester app it has x input supports and detected as Xbox One S.

**Comment by mytja** [comment]
So this is either a problem with your kernel or Android as a whole. I doubt it's the kernels, so this should be reported to Google. I highly doubt that Evolution X or I are removing touchpad support.
