### ISSUE TITLE
does not boot

### ISSUE THREAD

**Issue by Marcos-Dtel** [mytja/treble_evo#5]
it doesn't boot, and it doesn't even leave the manufacturer's logo, after a few minutes it restarts and goes back to GSI stock, so I can't even provide logs, what I can say is that my processor is an mtk helio p22 and my kernel is 4.19, I tested via DSU

**Comment by mytja** [comment]
Hey! Without logs it's hard for me to troubleshoot, however pretty much nothing can be done to obtain logs due to ADB likely being disabled on that stage of boot. However, I've noticed I've skipped some BPF patches (don't know how) from TrebleDroid, so that might be a culprit. I'll send you another test slim build once it finishes compiling. If that one doesn't boot, I sadly can't help without any logs...

**Comment by mytja** [comment]
Please download it from following page and let me know how it goes.

https://git.severkar.eu/mytja/treble_evo_test/releases/tag/20240905-test1-bpf

**Comment by Marcos-Dtel** [comment]
Okay bro

Em qui., 5 de set. de 2024, 18:43, Mitja Ševerkar ***@***.***>
escreveu:

**Comment by Marcos-Dtel** [comment]
Hello friend, I come here to thank you for the support and attention given to my case, the GSI started up, but it took about 2 minutes for the manufacturer's logo, and about 3 minutes for the evoX logo, this only happens on the first boot, other things that I noticed that do not work correctly, the access point pop-up, in the quick settings it is the pocket mode, at least for me those were the only ones, anyway thank you.

**Comment by Marcos-Dtel** [comment]
Oh yes, the slim version doesn't have a pre-installed apk of files, I had to go into the settings and open the file manager there but this can easily be solved with the playstore app╰(*°▽°*)╯

**Comment by mytja** [comment]
I'm glad it works. I'll push an OTA update later today with the patches, it's quite late in my timezone now :sweat_smile:.

**Comment by mytja** [comment]
![Screenshot_20240906-010014_Pixel Launcher.png](https://github.com/user-attachments/assets/1817616a-3f46-45ae-af5d-701a45c9947c)

The hotspot/access point dialog should be available through the Internet tile. Are you sure it isn't available?

**Comment by Marcos-Dtel** [comment]
https://github.com/user-attachments/assets/bc16fab2-e65a-4b06-9fac-c84421cd1194

**Comment by mytja** [comment]
I see. It doesn't open for me either, unless I hold on the hotspot "tile". I guess that's not how Evolution X devs/Android developers intended us to do :sweat_smile:. It doesn't seem like a problem with GSI but more with a specific ROM/Android as a whole.

I'll close the issue now. Should you have any additional questions, do not hesitate to ask. Thank you for opening this issue in the first place and bringing this to my attention.

**Comment by Marcos-Dtel** [comment]
Hi friend, I don't know if it works for you, but the screenshot with 3 fingers slider doesn't work.

**Comment by Marcos-Dtel** [comment]
https://github.com/user-attachments/assets/c273c7b0-9d76-4a7b-80a5-6651de821d84

I put this through magisk module 😄

**Comment by mytja** [comment]
> Hi friend, I don't know if it works for you, but the screenshot with 3 fingers slider doesn't work.

You can enable that feature through Evolver -> Gestures -> Three finger swipe gestures. For me it does work after enabling it.

**Comment by Marcos-Dtel** [comment]
![Screenshot_20240906-080322_Configurações](https://github.com/user-attachments/assets/7f8bc8b1-75c2-4e99-b0e9-d3881681d80f)
Unfortunately it doesn't work

**Comment by mitzamike** [comment]
> ![Screenshot_20240906-080322_Configurações](https://private-user-images.githubusercontent.com/179177849/365140935-7f8bc8b1-75c2-4e99-b0e9-d3881681d80f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjE0NjAsIm5iZiI6MTcyNTYyMTE2MCwicGF0aCI6Ii8xNzkxNzc4NDkvMzY1MTQwOTM1LTdmOGJjOGIxLTc1YzItNGU5OS1iMGU5LWQzODgxNjgxZDgwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxMTEyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDQ2Yzg2YTc3OTM0MjE5NDVkNTNlMGI5YTAyMjFiYmE4N2I0NWE2ZDcxOGZkNTc1MjY5YjIzMmEwZWI1Mjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GI30qk_Oci7z3aSA7YgJ5hw3RNQ7nzMplb0juK3wdzY) Unfortunately it doesn't work

Works just fine for me on my Samsung Galaxy A53 5G (SM-A536B). Latest slim build.

**Comment by Marcos-Dtel** [comment]
Well, after I unchecked and checked the option again and restarted a few times it worked, go figure
