### ISSUE TITLE
recommendation for the next update

### ISSUE THREAD

**Issue by HKMGER** [mytja/treble_evo#50]
I would like them to add an option that would allow changing the name of the ROM, for example, the default is evolution x gsi, but I would like to be able to change that name, for example, google pixel 9.
![Screenshot_20241020-124612_Configuración](https://github.com/user-attachments/assets/aa9c4c6e-f12d-4bc6-9f79-13895c8a95c0)
![4710](https://github.com/user-attachments/assets/5197b9a1-b7ca-4401-8085-645e63a22a7d)
![4709](https://github.com/user-attachments/assets/b7a5ab86-9f92-46fa-8caa-6b4d214e7aa2)
![4704](https://github.com/user-attachments/assets/59c3f9b1-a6fc-4899-8e6f-ef5d7d02f4b2)
and I would also like them to add Android 15
That's all thanks

**Comment by mytja** [comment]
Why would you need to change the model number?

Evolution X has not yet released A15, meaning I cannot upgrade. Once they do I'll make sure an A15 build comes out.
