### ISSUE TITLE
[request] auto increase brightness on lock screen for face unlock

### ISSUE THREAD

**Issue by carothersmarx** [mytja/treble_evo#52]
currently, face unlock is not usable in dim/dark environment and the only way to make it work is to manually increase the brightness of the screen which isn't ideal in night scenarios. most official roms opted to increase the brightness on lock screen and adjusted it again to what the user set after the screen is unlocked. having an option for this will make face unlock usable at night.

**Comment by mytja** [comment]
> which isn't ideal in night scenarios

I'd absolutely love a flashbang in the middle of the night.

> most official roms opted to increase the brightness on lock screen

Really? Don't know. I don't use face unlock.

**Comment by carothersmarx** [comment]
yeah you absolutely get flashbanged with it but i think an option for it is nice to have. 
and yeah, Samsung devices had this feature pretty much since they first had face unlock. it's called brighten screen and you can turn it off.

**Comment by mytja** [comment]
This should be relatively easy to add. I'll have a look.

**Comment by mytja** [comment]
Hi, this has been added in the latest beta release:

https://github.com/mytja/treble_evo/releases/tag/20241028

**Comment by naruto2038** [comment]
In version 9.5 Evolução X
![IMG-20241104-WA0001](https://github.com/user-attachments/assets/a9c7516d-b1a3-461f-89db-249f2a516933)
 on my Galaxy a54 device there is a bug that does not charge the phone in off mode. Can you fix this?
