### ISSUE TITLE
Tablet Bootloop (Evolution X 9.5 Beta)

### ISSUE THREAD

**Issue by Bushido1992** [mytja/treble_evo#54]
Hey,

today i updated to the 9.5 Beta und the Tablet has an Bootloop. 
The Tablet is an "LincPlus T3 Tablet" with an Mediatek 8781 Processor.

**Comment by mytja** [comment]
Have you updated from 9.5 stable to 9.5 beta or from earlier versions?

Do you have any custom recovery (such as TWRP/OrangeFox)? If so, please boot into recovery, do `adb pull /proc/last_kmsg` and send me the contents of it.

If not, that complicates the process a little bit. If the tablet bootloops on Evolution X logo, try catching logs using `adb logcat` and send me those logs.

If even that doesn't work, let me know and I'll try to make a test build with some commits reverted.

**Comment by Bushido1992** [comment]
ive updated from last stable (Evolution X 9.5 - 2024-10-12) to this beta. i have no custom recovery installed. i will flash now the beta again and try to catch logs if possible

**Comment by mytja** [comment]
Thanks for the log! It seems as if boot animation cannot be found (?)

Is it possible that you've had a custom boot animation on stable 9.5 and the Evolution X team has since then removed (or forgot to include) that boot animation, now not wanting to boot?

Can you please try clean flashing through DSU Sideloader and see if it'll boot that way? In any case, it doesn't seem to be an issue with sepolicy, so beta should boot as it did before.

**Comment by Bushido1992** [comment]
i had set the pac-rom animation(thats shows up). i´ve changet it to the normal Evolution X and flashd it again....same Problem

**Comment by mytja** [comment]
No need to backup data. Use DSU sideloader:

https://github.com/VegaBobo/DSU-Sideloader

It won't touch your data or your system.

**Comment by Bushido1992** [comment]
i tryd it with this tool taht took very long. after restart the Tablet the same :-/ Bootloop on the Logo

**Comment by mytja** [comment]
So if I understand correctly, it bootlooped twice, then proceeded to work?

**Comment by Bushido1992** [comment]
No. the starts took 3-5 Minutes on first Boot (thats why i´be thinked bootloop xD). But then the Android Setup started and Tablet "workd"

**Comment by mytja** [comment]
Oh, great. I don't know what's happening with the direct upgrade though. It's something weird with boot animations and I'm not really willing to investigate it.

If it's not too big of a burden for you, and you want to update to latest beta release, do a clean flash (of course do the backup and restore the backup later on). If not, stable 9.5 is also a great choice. Those issues might clean themselves up if Evolution X accidentally broke something.

In any case, thanks for your cooperation. That's more than I get from an average issue. If you have any further questions, I'm here to answer them.
