### ISSUE TITLE
Reality Display Engine causes the screen to turn completely white

### ISSUE THREAD

**Issue by carothersmarx** [mytja/treble_evo#55]
I'm not sure where to report this. In the latest 9.5 beta, selecting some reality display engine in display>colors made my screen to turn completely white, namely the sony ones (X reality, triluminous) making the device unusable until the option is switched back to default.
seems like a compatibility issue because it still displays just fine on scrcpy.

**Comment by carothersmarx** [comment]
sorry for the wait, here's the log
[logcat.txt](https://github.com/user-attachments/files/17660767/logcat.txt)

**Comment by mytja** [comment]
Sooo ... I've been checking ...

Reality engine display has been quietly removed from Evolution X's sources, meaning I will no longer compile it in upcoming versions. It's probable that it was extremely buggy, causing scenarios such as this one.

If it ever comes back and you have the same issue, please open a new issue and I'll have a look at it. Sorry for the unfortunate outcome.
