### ISSUE TITLE
Bluetooth issue 

### ISSUE THREAD

**Issue by Harshith566** [mytja/treble_evo#57]
Bluetooth works all fine and good but it keeps on disconnecting and reconnecting from the phone tried other roms but it seems fine on roms which are under android 14. Any fix for it?? Tried misc features too but no gud and I think force disable A2DP would do the job but phh treble doesn't has that option anymore and  in developer options it's grated out

**Comment by HKMGER** [comment]
It is a gsi error, try using this magisk module to fix it 
[Bluetooth_stack_audio_bitrate_changer_for_SBC_+_aptX_&_aptX-HD_enabler-v5.4(9).zip](https://github.com/user-attachments/files/18050006/Bluetooth_stack_audio_bitrate_changer_for_SBC_%2B_aptX_._aptX-HD_enabler-v5.4.9.zip)
Also in the active configuration these options 
![Screenshot_20241207-160656_PhhTrebleApp](https://github.com/user-attachments/assets/4b752871-d31e-4f3c-8f31-133fe9cd22fc)

**Comment by mytja** [comment]
Try again in the newest release. If it's a TrebleDroid issue, I likely won't fix it.
