### ISSUE TITLE
OTA updater

### ISSUE THREAD

**Issue by mitzamike** [mytja/treble_evo#6]
The OTA updater detects an update even though I'm already on the latest version of the GSI. Is this behaviour normal?
![Screenshot_20240906-021805_PhhTrebleApp](https://github.com/user-attachments/assets/fa7fe9c5-e6f4-4076-bab4-9675555bfc75)

**Comment by mytja** [comment]
It is not normal. I'll fix it later today.

**Comment by mitzamike** [comment]
> It is not normal. I'll fix it later today.

Will we be able to update using the OTA updater after you push the fix?

If not, how do you update a GSI without OTA? I've never done it before so I don't know.
I have TWRP, so I'm guessing I just have to flash the new image and then reboot to system? Or are there any other steps?

**Comment by mytja** [comment]
> Will we be able to update using the OTA updater after you push the fix?

Yeah, you should be. If you have Magisk, it's not really recommended to update through OTA though. As for KernelSU, it's probably fine.

> If not, how do you update a GSI without OTA? I've never done it before so I don't know.
I have TWRP, so I'm guessing I just have to flash the new image and then reboot to system? Or are there any other steps?

That's all. Just flash the image to system partition from TWRP or reboot to fastboot mode from TWRP and execute `fastboot flash system name-of-system-image.img` on your computer. In both of these cases no additional steps are required.

**Comment by mitzamike** [comment]
Yippee thanks for update, updated through OTA successfully


![Screenshot_20240906-223101_PhhTrebleApp](https://github.com/user-attachments/assets/62aa1e68-fc70-4d76-8e62-c78983ca4668)

**Comment by mitzamike** [comment]
> > Will we be able to update using the OTA updater after you push the fix?
> 
> Yeah, you should be. If you have Magisk, it's not really recommended to update through OTA though. As for KernelSU, it's probably fine.
> 
> > If not, how do you update a GSI without OTA? I've never done it before so I don't know.
> > I have TWRP, so I'm guessing I just have to flash the new image and then reboot to system? Or are there any other steps?
> 
> That's all. Just flash the image to system partition from TWRP or reboot to fastboot mode from TWRP and execute `fastboot flash system name-of-system-image.img` on your computer. In both of these cases no additional steps are required.

Question, if I wanna switch from slim version to normal one without losing data, can I just dirty flash it?

**Comment by mytja** [comment]
Yep, it should work.
