### ISSUE TITLE
GSI 9.5 Evolution X Does not charge power when the device is turned off.

### ISSUE THREAD

**Issue by jhonnchefe** [mytja/treble_evo#60]
My cell phone does not charge when turned off, I am on version 9.5 of Evolution X, this is very serious and needs to be fixed urgently. Galaxy A546E.
![IMG-20241104-WA0001](https://github.com/user-attachments/assets/46a76f57-138e-4e8a-bf75-7d7314609a8c)

**Comment by mytja** [comment]
> My cell phone does not charge when turned off
It does charge, it just doesn't display it's charging.

> this is very serious and needs to be fixed urgently
No. I am aware of this issue, it's some crap with Samsung's vendor libraries for which I honestly do not have the will to debug. As stated before, your phone charges, it just doesn't display it. To boot back into the system, hold volume down and power button at the same time.

**Comment by naruto2038** [comment]
I managed to turn it on with the tip you gave me, thank you very much, I really like this GSI, it is very good except for this problem and the fingerprint problem, I didn't find any other bugs, I hope that in the future these 2 bugs will be fixed because this is the best GSI I have tested.

**Comment by mytja** [comment]
Fixed in the newest release.

https://github.com/mytja/treble_evo/releases/tag/20241226
