### ISSUE TITLE
some improvements to be implemented on Samsung devices.

### ISSUE THREAD

**Issue by naruto2038** [mytja/treble_evo#61]
Add a power profile to avoid unnecessary power usage/battery drain

Status bar height needs to be fixed

Android needs to respect the presence of the hole punch

Status bar elements need to be bottom-aligned, similar to stock firmware

Fixed rounded corner padding

More accurate rounded corner padding

Fix Always-On Display (AOD)

Enable burn-in protection by shifting UI elements (like stock firmware)

Enable 25W fast charging

Enable dynamic refresh rate

Reduces refresh rate from 120Hz to 60Hz when content is static, to save battery

**Comment by mytja** [comment]
> Add a power profile to avoid unnecessary power usage/battery drain

Your device doesn't have a treble overlay.

> Status bar height needs to be fixed

Your device doesn't have a treble overlay.

> Android needs to respect the presence of the hole punch

Your device doesn't have a treble overlay.

> Status bar elements need to be bottom-aligned, similar to stock firmware

This isn't stock firmware if you haven't noticed yourself.

> Fixed rounded corner padding

Your device doesn't have a treble overlay.

> More accurate rounded corner padding

Your device doesn't have a treble overlay.

> Fix Always-On Display (AOD)

Your device doesn't have a treble overlay.

> Enable burn-in protection by shifting UI elements (like stock firmware)

Your device doesn't have a treble overlay.

> Enable 25W fast charging

Your device doesn't have a treble overlay.

> Enable dynamic refresh rate

Your device doesn't have a treble overlay.

> Reduces refresh rate from 120Hz to 60Hz when content is static, to save battery

No.

**Comment by mytja** [comment]
I've just noticed your device has just recently received a treble overlay. In any case it'll be included in new builds.

**Comment by naruto2038** [comment]
thanks🫡
