### ISSUE TITLE
Gestures got confused with landscape/portrait on recent app switching

### ISSUE THREAD

**Issue by carothersmarx** [mytja/treble_evo#62]
sorry for yet another issue.

gesture navigation often got "confused" when i switched between a fullscreen landscape app (like a game) and a regular portrait app. the gesture behavior from the full screen app retains when i switched to the portrait app and vice versa. so the back gesture often ended up not working and swiping to the right shows the recent app list instead, for example. this is fixable by either terminating the full screen or going back to the recent app screen again, but this is kinda annoying.

i don't use a custom launcher, so quickswitch should sill be the default from pixel launcher.

**Comment by mytja** [comment]
I tried answering a couple of days ago, but I gave up as GitHub didn't want to upload my video. So I'm trying again.

I can't really reproduce the issue and I'm afraid it won't be in logs... I can't really help on this one, sorry.

https://github.com/user-attachments/assets/05ae5832-b524-4a8c-aabf-da22a4e7ef98
