### ISSUE TITLE
under-screen fingerprint sensor isn't detecting on TECNO PHANTOM X2

### ISSUE THREAD

**Issue by Idragon01** [mytja/treble_evo#65]
When I select digital fingerprint it says that the under-screen fingerprint sensor is on the back of the phone so that's wrong. if anyone has a solution this is the only problem i have

**Comment by mytja** [comment]
If this happens on all GSIs, it's the problem with your hardware overlay. I see that your device doesn't have it. Please make it according to https://github.com/phhusson/treble_experimentations/wiki/How-to-create-an-overlay%3F and either:

1. submit it yourself to https://github.com/TrebleDroid/vendor_hardware_overlay
2. send it to me & I'll make a pull request to TrebleDroid sources

**Comment by Idragon01** [comment]
> Si cela se produit sur tous les GSI, le problème vient de votre overlay matériel. Je vois que votre appareil n'en est pas équipé. Veuillez le faire conformément à https://github.com/phhusson/treble_experimentations/wiki/How-to-create-an-overlay%3F et soit :
> 
> 1. soumettez-le vous-même à https://github.com/TrebleDroid/vendor_hardware_overlay
> 2. envoie-le moi et je ferai une demande d'extraction aux sources de TrebleDroid

Do I just send the system partition or the entire firmware?

**Comment by mytja** [comment]
Oh, I meant create the appropriate XML overlay. Or just send me the link to download firmware for your phone and I'll take care of the rest.

**Comment by Idragon01** [comment]
> Oh, je voulais dire créer la superposition XML appropriée. Ou envoyez-moi simplement le lien pour télécharger le firmware de votre téléphone et je m'occuperai du

> Oh, I meant create the appropriate XML overlay. Or just send me the link to download firmware for your phone and I'll take care of the rest.

you can download it here https://drive.google.com/file/d/1kHcau-o60TrToo3MypPl8iHPwIvCsHxd/view

it's android version 12 I don't have version 13 is that enough

**Comment by mytja** [comment]
Thanks! It's probably enough. Your overlay should be done by the end of tomorrow (Monday). I'll send you a Magisk/KernelSU module to test whether the overlay works or not before sending the pull request to TrebleDroid team.

**Comment by Idragon01** [comment]
> Oh, I meant create the appropriate XML overlay. Or just send me the link to download firmware for your phone and I'll take care of the rest.

you can download it here https://drive.usercontent.google.com/download?id=1kHcau-o60TrToo3MypPl8iHPwIvCsHxd&export=download&authuser=0

it's android version 12 I don't have version 13 is that enough

**Comment by Idragon01** [comment]
> Thanks! It's probably enough. Your overlay should be done by the end of tomorrow (Monday). I'll send you a Magisk/KernelSU module to test whether the overlay works or not before sending the pull request to TrebleDroid team.

No, it's me who thanks you for your help! THANK YOU

**Comment by Idragon01** [comment]
> Bonjour à nouveau,
> 
> C'est maintenant fait. Veuillez d'abord flasher le module test1 dans Magisk/KernelSU et redémarrer dans le GSI. Cela ne fonctionnera probablement pas car je n'ai vu aucun paramètre d'empreinte digitale, mais cela vaut la peine d'essayer.
> 
> Si le module test1 ne résout pas le problème dans une situation différente, essayez le module test2. Encore une fois, installez-le dans Magisk/KernelSU et redémarrez dans le GSI. Si cela ne fonctionne pas, alors je n'ai plus d'idées, mais cela devrait fonctionner.
> 
> Veuillez m'informer des résultats afin que je sache si je peux les envoyer à l'équipe TrebleDroid pour les inclure dans tous les GSI.
> 
> Module test1 : [tecno-phantom-x2-5g-overlay-test1.zip](https://github.com/user-attachments/files/17693099/tecno-phantom-x2-5g-overlay-test1.zip) Module test2 : [tecno-phantom-x2-5g-overlay-test2.zip](https://github.com/user-attachments/files/17693100/tecno-phantom-x2-5g-overlay-test2.zip)

I can't flash it 
![Screenshot_20241110-215222](https://github.com/user-attachments/assets/968b69df-b4b0-40fe-9993-5565a5358e51)

**Comment by mytja** [comment]
Strange. I can flash both without a problem. Maybe recheck that your downloads aren't corrupt. If you've ever had such an issue before, maybe try installing osm0sis' Busybox Installer.

![Screenshot_20241110-230642_KernelSU.png](https://github.com/user-attachments/assets/6dfe805f-4ad9-4dbc-97a3-3268d6298a7d)

**Comment by Idragon01** [comment]
> Étrange. Je peux flasher les deux sans problème. Peut-être devriez-vous revérifier que vos téléchargements ne sont pas corrompus. Si vous avez déjà eu un tel problème auparavant, essayez peut-être d'installer l'installateur Busybox d'osm0sis.
> 
> ![Capture d'écran_20241110-230642_KernelSU.png](https://private-user-images.githubusercontent.com/52399966/384729534-6dfe805f-4ad9-4dbc-97a3-3268d6298a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNzcxNTUsIm5iZiI6MTczMTI3Njg1NSwicGF0aCI6Ii81MjM5OTk2Ni8zODQ3Mjk1MzQtNmRmZTgwNWYtNGFkOS00ZGJjLTk3YTMtMzI2OGQ2Mjk4YTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDIyMTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYzRhOTBkMmZlMGViMzM0ZDc4OWJkODYxOTJhZjU4MWU2YmExYTU4ZTEwYWM4ODI3ZmQ4NzQ3ZDE1NjZkYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HzdG4KRhgGA6dMAjbQfzQ43OPR10Mj7rlhaElnlpNWQ)

I will try with KernelSu

**Comment by Idragon01** [comment]
> Étrange. Je peux flasher les deux sans problème. Peut-être devriez-vous revérifier que vos téléchargements ne sont pas corrompus. Si vous avez déjà eu un tel problème auparavant, essayez peut-être d'installer l'installateur Busybox d'osm0sis.
> 
> ![Capture d'écran_20241110-230642_KernelSU.png](https://private-user-images.githubusercontent.com/52399966/384729534-6dfe805f-4ad9-4dbc-97a3-3268d6298a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyODMyMjgsIm5iZiI6MTczMTI4MjkyOCwicGF0aCI6Ii81MjM5OTk2Ni8zODQ3Mjk1MzQtNmRmZTgwNWYtNGFkOS00ZGJjLTk3YTMtMzI2OGQ2Mjk4YTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDIzNTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MjAwZTg5ODliNmJiZjhhZWYzMDkwYzY5MjM3ZWRhZDgzNWVlNmM1ZGVhOTA4NDhjOWQyMDMwZjFkMGNlNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IpsEHyFsRgnWeOuUrEsgIzRBQYe8K4iaVYClVYTcEjo)

I flash it but don't work
![Uploading Screenshot_20241110-235428_KernelSU.png…]()

**Comment by mytja** [comment]
Not even the second one?

**Comment by Idragon01** [comment]
This one is in my Stock rom
[TEST1.txt](https://github.com/user-attachments/files/17700643/TEST1.txt)



> Pas même le deuxième ? Si c'est le cas, pouvez `adb shell getprop ro.product.vendor.device`-vous m'envoyer le résultat ?

I tested this one in my stock rom 
[TEST1.txt](https://github.com/user-attachments/files/17700652/TEST1.txt)

This one with GSI 
[TEST2.txt](https://github.com/user-attachments/files/17700658/TEST2.txt)

**Comment by mytja** [comment]
Hey! Sorry for the late reply, was busy with many things. I think I've done everything correctly. I see no practical difference from the Camon 20 Pro 4G overlay, which also has FOD.

It might be that your overlay isn't enabled. If you're using DSU sideloader, I think KernelSU doesn't work with it very well. Would you mind executing `adb shell cmd overlay list --user current` and sending me the output on latest Evolution X GSI? Perhaps you could also send me the output of this one: `adb shell ls /system/product/overlay/`.

I really wouldn't know what's wrong if overlay is enabled though. We'll see.

**Comment by Idragon01** [comment]
> adb shell ls /system/product/overlay/

Thank you for taking the time to answer me maybe if I flash the GSI on the phone permanently it will solve the problem? This is what I wanted to do from the beginning but it is the fingerprint sensor problem that stop me
[First command.txt](https://github.com/user-attachments/files/17773708/First.command.txt)
[Second command.txt](https://github.com/user-attachments/files/17773714/Second.command.txt)

**Comment by mytja** [comment]
Well, (un)fortunately the overlay seems to be enabled. I have no idea what's going wrong.

Does this happen only on Evolution X GSI or does it happen on all A14 GSIs? Does it happen on Android 13/Android 12 GSIs?

**Comment by Idragon01** [comment]
> Eh bien, (mal)heureusement, la superposition semble être activée. Je n'ai aucune idée de ce qui ne va pas.
> 
> Cela se produit-il uniquement sur Evolution X GSI ou sur tous les A14 GSI ? Cela se produit-il sur les GSI Android 13/Android 12 ?

I have the same problem on all the GSI that I tested but I did not test on A13 or A12 Good Thanks for the help you gave me now I have to be content to use my stock rom even if it is ugly.  
I would like to ask you I want to install a custom recovery on my smartphone but it has no recovery partition and even when I try to boot twrp with the fastboot command it doesn't work
