### ISSUE TITLE
Samsung Galaxy A32 SMS Fix module not working

### ISSUE THREAD

**Issue by Vad1mCSO2** [mytja/treble_evo#7]
https://xdaforums.com/t/solved-gsi-related-can-not-receive-sms.4636173/
https://xdaforums.com/t/solved-gsi-related-can-not-receive-sms.4636173/#post-89155753
This KernelSU[Forms KernelSuperUser] module not working. works fine on EvoX VIII

**Comment by Vad1mCSO2** [comment]
Also headphone jack not working

**Comment by mytja** [comment]
MTK devices might need additional kernel modules for RIL rollback to function. Try installing MTK IMS from Phh Treble Settings if you have the option. Additional option is to install FOSS IMS and see if that fixes SMS.

Headphone jack is finicky. Not sure what causes this, but a dirty reflash over the same version fixed the issue for me (apart from running some commands, so I'm not sure which one exactly fixed it). Also make sure you have "Phh Treble Settings > Samsung features > Use alternate audio policy" turned on.

**Comment by Vad1mCSO2** [comment]
Where's MTK IMS from PHH TS. I can't find it

**Comment by mytja** [comment]
> Using alternative audio policy that breaks the volume effects

There's no other way for wired headphones support other than that. MTK IMS should be able to be installable through Phh Treble Settings > IMS festires > Install IMS APK for MTK or something similar. I'm not sure it exists, but I think it does... I'm unsure.

**Comment by Vad1mCSO2** [comment]
![Screenshot_20240906-160823_PhhTrebleApp](https://github.com/user-attachments/assets/8c50fe0a-6ef7-45ff-b317-649ac44ac7e4)

**Comment by mytja** [comment]
Try installing FOSS IMS. You can find the link to it on previoud release. Also make sure to click Create IMS APN in Phh treble settings after installing FOSS IMS. Restart may be required.

**Comment by Vad1mCSO2** [comment]
When I clicking Create IMS APN does nothing. I clicked after install, reboot, and sms not receiving

**Comment by mytja** [comment]
Sadly I wouldn't know then... Maybe try logcat to see why the RIL rollback doesn't work. It should work like on other GSIs.

**Comment by Vad1mCSO2** [comment]
[0003.txt](https://github.com/user-attachments/files/16906376/0003.txt)

**Comment by mytja** [comment]
Unfortunately nothing related to radio is here, apart from failing Qualcomm RIL, however that should be unrelated.

Are you sure the module is enabled and working? KernelSU has an A/B-like system with modules. If boot with new modules fails, it disables them (but still display them as enabled in their manager app), but doesn't notify the user about that.

**Comment by Vad1mCSO2** [comment]
Module SMS Fix is enabled and not working. I using bgN [A/B Partition, Google Apps, no root built-in(Root append)]. there are no issues with EvoX VIII. that module was outdated

**Comment by Vad1mCSO2** [comment]
This model is SM-A325F/DS

**Comment by Vad1mCSO2** [comment]
I installed the latest build but receive SMS and calls not working

**Comment by Vad1mCSO2** [comment]
My binary is 8

**Comment by mytja** [comment]
Look, trying to contact me on my personal platforms (Discord) isn't going to work. SMS fix has nothing to do with the GSI. I am using all RIL patches from TrebleDroid. Test out LineageOS GSI, they have the same telephony library, as EvoX is based on it. There's clearly something wrong with the module if it doesn't work.

What's going on with /vendor is not a problem with GSI (generic SYSTEM image), but a problem with /vendor. Go ahead and write an e-mail to Samsung and ask them to fix it.

**Comment by mytja** [comment]
Also here is some guy with the same issue. https://xdaforums.com/t/sms-fix-for-exynos-devices-running-a-gsi.4658849/post-89692512

**Comment by mytja** [comment]
I've tried extending the MTK RIL rollback. Would you mind checking if this Magisk module works?

[SMS_Temp_fix_A32.zip](https://github.com/user-attachments/files/16933593/SMS_Temp_fix_A32.zip)

**Comment by Vad1mCSO2** [comment]
> I've tried extending the MTK RIL rollback. Would you mind checking if this Magisk module works?
> 
> [SMS_Temp_fix_A32.zip](https://github.com/user-attachments/files/16933593/SMS_Temp_fix_A32.zip)

I'm using KernelSU to install magisk module but, stuck on boot. I will wiping to data to reset to factory

**Comment by mytja** [comment]
No, no. Don't wipe data! KernelSU has a built in bootloop protector, just force a restart using Power button + volume down and you'll be able to boot into system and be able to remove the module. Didn't know you were using KSU.

**Comment by Vad1mCSO2** [comment]
> Headphone jack is finicky. Not sure what causes this, but a dirty reflash over the same version fixed the issue for me (apart from running some commands, so I'm not sure which one exactly fixed it). Also make sure you have "Phh Treble Settings > Samsung features > Use alternate audio policy" turned on.

This resolves at Phh Treble Settings ► Misc Features ► Use alternate way to detect headsets
