### ISSUE TITLE
They could add some functions 🥺

### ISSUE THREAD

**Issue by HKMGER** [mytja/treble_evo#71]
Could you add the 3d wallpaper feature that comes included In the screen and style app. Also, if you could fix the error of the edges on the screen since they come out in white and not in the color I choose and you could put the aod

**Comment by mytja** [comment]
> Could you add the 3d wallpaper feature that comes included In the screen and style app

Please contact the Evolution X team about that.

> Also, if you could fix the error of the edges on the screen since they come out in white and not in the color I choose

Maybe an overlay would fix that? I'm not sure what does this even mean.

> you could put the aod

There already is AOD. If it isn't available for your device, I think it should be somewhere in the Treble App.
