### ISSUE TITLE
When android 16?

### ISSUE THREAD

**Issue by Mod4-Da-GOAT** [mytja/treble_evo#75]
Look this might seem like a joke but honestly I wanna know if u will make evolution x android 16 dev preview

**Comment by mytja** [comment]
Lmao this indeed sounds like a joke. I will be building GSIs as long as my phone doesn't have a device tree. And even after then I'll try building GSIs and ROMs in conjunction. Only GSIs might be delayed. Well, my device won't get a device tree for long time, so I guess yeah, you can expect A16.

**Comment by Mod4-Da-GOAT** [comment]
Ok thx for the help
