### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by Mod4-Da-GOAT** [mytja/treble_evo#76]
Added "Brighten screen" feature inside Phh Treble Settings > Misc settings > User interface

So based on this I think the brightness issue for Samsung a23 I texted u on email about, so am I right or wrong?

**Comment by mytja** [comment]
Brighten screen doesn't have anything to do with fixing device brightness issues. It's a feature that allows for Face Unlock to brighten the screen up while attempting to unlock your phone.

**Comment by Mod4-Da-GOAT** [comment]
Ok mb
