### ISSUE TITLE
I just have 5 questions

### ISSUE THREAD

**Issue by Mod4-Da-GOAT** [mytja/treble_evo#82]
Does evo x come with root or do I have to root first?
How to flash a Samsung (bcs I have a Samsung too)?
Does it support 2 SIM cards?
(I just remember these 3 for now when I remember the rest I’ll open another issue btw mb for asking too many questions)

**Comment by mytja** [comment]
> Does evo x come with root or do I have to root first?

Root with Magisk/KernelSU/APatch. Evolution X does not come with any root-based solutions.

>  How to flash a Samsung (bcs I have a Samsung too)?

Flash the .img file using `fastboot` if you're using a [fastboot-enabled recovery](https://github.com/Johx22/Patch-Recovery) or TWRP/any custom recovery if your device has it.

>  Does it support 2 SIM cards?

Yes. It should support everything that TD supports.

**Comment by Mod4-Da-GOAT** [comment]
Can I update if I root tho?

**Comment by mytja** [comment]
Of course. Maybe not through the OTA updater, but through fastboot/TWRP, sure.

**Comment by Mod4-Da-GOAT** [comment]
Do I need to root to flash through twrp though?

**Comment by mytja** [comment]
No.
