### ISSUE TITLE
no audio in sim 2.

### ISSUE THREAD

**Issue by Mozahid007** [mytja/treble_evo#85]
There's no in-call audio in Sim2. Everything works fine with Sim 1. Is it a common gsi issue in Samsung? Is there any fix for the in-call audio in Sim 2? device model is galaxy f23 5g.

**Comment by mytja** [comment]
It's likely a TrebleDroid issue, so I'm unlikely to fix it. Report it at [TrebleDroid issue tracker](https://github.com/TrebleDroid/treble_experimentations/issues) if it happens even in their own builds.
