### ISSUE TITLE
Is there any fix for network traffic indicator not working in evox 9.6??

### ISSUE THREAD

**Issue by Technical06** [mytja/treble_evo#88]
i have previously reported the same issue but there was no solution provided , so i just wanted to ask if theres anything i can do to fix this?

**Comment by mytja** [comment]
> Network traffic indicator not working from quite some time in every A14 build

This seems like the most active issue going forward, so please subscribe to that one. I'll still try fixing the problem despite it being a kernel issue.

https://github.com/mytja/treble_evo/issues/79
