### ISSUE TITLE
broken bluetooth 9.7

### ISSUE THREAD

**Issue by Doze-off** [mytja/treble_evo#94]
[2024-12-22-18-04-36-bluetooth.txt](https://github.com/user-attachments/files/18223229/2024-12-22-18-04-36-bluetooth.txt)
compared to version 9.6 now bluetooth is broken, in version 9.6 it worked perfectly
mtk helio p22 processor

**Comment by mytja** [comment]
I see. I've looked again at Bluetooth patches and I can only find a single thing that could be the cause for it, but that thing is very likely to be causing the problem.

It seems as if I missed some things during manual application. You can expect a new build around in a couple of days (let's say around Christmas), as I'm currently experimenting with Android 15. Meanwhile, you can try downgrading if possible (if it'll bootloop after downgrading, you'll unfortunately need to stick to 9.7).

If I forget, feel free to @mytja (ping) me, and I'll make sure it gets resolved ASAP.

Note to self (reintroduce that massive removed block):
https://github.com/mytja/treble_evo_patches/commit/880c973267253973064437c740508a11779f3f45#diff-bb4446e262ae2895d674a36bb15d2fa7fd63a9fbe12698e0f3b858948ace4b34

**Comment by mytja** [comment]
Please try again in the newest release. Reopen the issue if it still doesn't work.

**Comment by Doze-off** [comment]
@mytja Congratulations on your work, I brought the backport of Android 15, now I don't even need to change the phh settings to fix the bluetooth, I haven't had time lately to test the versions that have come out Previously, but I tested it yesterday, it's excellent, but one thing that happens, only on the evo x, a small delay, when pressing any volume button, the panel always arrives late,I don't know if it's from the evo x's own source, but anyway. Have a great end of the year.
