### ISSUE TITLE
USB Connection Issue - Device Charges but Not Recognized for Data Transfer

### ISSUE THREAD

**Issue by lam1623** [mytja/treble_evo#95]
I recently updated my device to the latest version of Evolution X (version 9.7, released on December 22, 2024). However, I'm experiencing an issue where the device only charges when connected to a PC via USB, but the computer does not recognize it for data transfer.

Steps to reproduce:

Connect the device to a PC using a USB cable.
The device begins charging, but it is not detected for file transfer.
Expected behavior:

The device should be recognized by the PC for data transfer and allow file access.
Any assistance or guidance would be greatly appreciated.

Samsung Galaxy Tab A7 Lite (SM-T227U)

**Comment by SMOLKEYS** [comment]
> I recently updated my device to the latest version of Evolution X (version 9.7, released on December 22, 2024). However, I'm experiencing an issue where the device only charges when connected to a PC via USB, but the computer does not recognize it for data transfer.
> 
> Steps to reproduce:
> 
> Connect the device to a PC using a USB cable. The device begins charging, but it is not detected for file transfer. Expected behavior:
> 
> The device should be recognized by the PC for data transfer and allow file access. Any assistance or guidance would be greatly appreciated.
> 
> Samsung Galaxy Tab A7 Lite (SM-T227U)

1. Did you set the configuration on the phone to enable file transfer? (Settings > System > USB configuration)
2. If applicable in the Treble app, did you enable USB OTG in there? (Settings > Phh Treble Settings > <`specific per device.`>)
