### ISSUE TITLE
Evo launcher

### ISSUE THREAD

**Issue by jonesty09** [mytja/treble_evo#98]
First of all I am really loving the work you put into this rom. This really is my go to and I never had such a seamless experience! However something I am missing form this evolution x version is the option to use the Evo launcher, because I would really like to use themed icons and force the ones that don't support it. it would be a nice option for people like me. Nevertheless this rom really is fantastic! Merry Christmas 🎄🎁.

**Comment by mytja** [comment]
Hi,

Please refer to the answer in issue #97.

Let me know if you need any additional clarifications.

Have a nice day.
