### ISSUE TITLE
BT does not work

### ISSUE THREAD

**Issue by Trommel2** [mytja/treble_evo#99]
The build 9.7 boots on Unihertz Pocket. Mediatek P60. Mediatek BloeTooth workarounds are activated in the PHH settings. The only problem: BlueTooth does not work. Is there possibly a patch or a workaround to activate it? NFC works. 
In 9.6, BT deactivated after a few seconds after pairing.
I don't want to downgrade to 9.6 because everything else works to my satisfaction. 
Many thanks for the great work and a Merry Christmas!

**Comment by mytja** [comment]
#94
